INSERT INTO HEALTHRECORD(SNO,NAME,CITY,AGE,GEN)
VALUES(1,'NEELESH','RAIPUR',25,'M'),
(2,'MOHIT','JAIPUR',35,'M'),
(3,'NIKHIL','MUMBAI',30,'F'),
(4,'PAWAN','DELHI',50,'M'),
(5,'SANJEEV','PATNA',45,'F');